package com.bulkcarrier.interviewtrainer;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.graphics.Color; import android.os.*; import android.view.*; import android.widget.*; import java.util.*;
public class MainActivity extends Activity{
 ArrayList<Question> all; LinearLayout listLayout; Spinner spinner; EditText search; CheckBox readRu; String section="All sections"; int primary=Color.rgb(11,61,98);
 public void onCreate(Bundle b){super.onCreate(b); all=QuestionRepository.load(this); if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5); ui(); render();}
 TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(6,6,6,6);return v;} Button bt(String s){Button b=new Button(this);b.setText(s);return b;}
 void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(244,247,251));
  TextView title=tv("Bulk Carrier Interview Trainer",20,Color.WHITE);title.setBackgroundColor(primary);title.setPadding(22,22,22,8);root.addView(title);
  TextView sub=tv("Native APK — screen-off foreground audio",13,Color.WHITE);sub.setBackgroundColor(primary);sub.setPadding(22,0,22,16);root.addView(sub);
  LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(14,14,14,8);c.setBackgroundColor(Color.WHITE);
  search=new EditText(this);search.setHint("Search: SOLAS, liquefaction, PSC...");search.setSingleLine(true);c.addView(search);
  ArrayList<String> secs=new ArrayList<>();secs.add("All sections");for(Question q:all)if(!secs.contains(q.section))secs.add(q.section);spinner=new Spinner(this);spinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,secs));c.addView(spinner);
  readRu=new CheckBox(this);readRu.setText("Read Russian explanation");readRu.setChecked(true);c.addView(readRu);
  LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);String[] names={"▶ Play all","⏸ Pause","▶ Resume","⏹ Stop"};for(String n:names){Button bb=bt(n);row.addView(bb,new LinearLayout.LayoutParams(0,-2,1)); if(n.contains("Play all"))bb.setOnClickListener(v->start(-1)); else if(n.contains("Pause"))bb.setOnClickListener(v->act(AudioPlayerService.ACTION_PAUSE)); else if(n.contains("Resume"))bb.setOnClickListener(v->act(AudioPlayerService.ACTION_RESUME)); else bb.setOnClickListener(v->act(AudioPlayerService.ACTION_STOP));} c.addView(row); root.addView(c);
  spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int pos,long id){section=p.getItemAtPosition(pos).toString();render();}public void onNothingSelected(AdapterView<?> p){}});
  search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){} public void onTextChanged(CharSequence s,int st,int b,int c){render();} public void afterTextChanged(android.text.Editable e){}});
  ScrollView sv=new ScrollView(this);listLayout=new LinearLayout(this);listLayout.setOrientation(LinearLayout.VERTICAL);listLayout.setPadding(10,10,10,20);sv.addView(listLayout);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 ArrayList<Question> filt(){ArrayList<Question> r=new ArrayList<>();String term=search==null?"":search.getText().toString().toLowerCase().trim();for(Question q:all){String hay=(q.section+" "+q.q+" "+q.a+" "+q.ru).toLowerCase();if((section.equals("All sections")||q.section.equals(section))&&(term.isEmpty()||hay.contains(term)))r.add(q);}return r;}
 void render(){if(listLayout==null)return;listLayout.removeAllViews();ArrayList<Question> items=filt();listLayout.addView(tv(items.size()+" / "+all.size()+" questions",14,Color.DKGRAY));for(Question q:items){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(18,18,18,18);card.setBackgroundResource(R.drawable.card_bg);card.addView(tv(q.id+". "+q.section,13,primary));TextView qu=tv("Question: "+q.q,18,Color.rgb(16,32,48));qu.setTypeface(null,1);card.addView(qu);card.addView(tv("Answer: "+q.a,15,Color.rgb(20,50,74)));card.addView(tv("Объяснение: "+q.ru,15,Color.rgb(60,50,30)));Button p=bt("▶ Play from here");p.setOnClickListener(v->start(q.id));card.addView(p);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,14);listLayout.addView(card,lp);}}
 void start(int id){Intent i=new Intent(this,AudioPlayerService.class);i.setAction(id>0?AudioPlayerService.ACTION_PLAY_FROM:AudioPlayerService.ACTION_PLAY_ALL);i.putExtra(AudioPlayerService.EXTRA_START_ID,id);i.putExtra(AudioPlayerService.EXTRA_SECTION,section);i.putExtra(AudioPlayerService.EXTRA_READ_RU,readRu.isChecked()); if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
 void act(String a){Intent i=new Intent(this,AudioPlayerService.class);i.setAction(a); if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
}
